config/routes.rb
Rails.application.routes.draw do

  get 'index',to:'welcome#index'
  get 'mobile', to: 'welcome#index_mobile'

   root 'welcome#index'

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  Browser::Base.include(Browser::Aliases)
  def index
    @browser = Browser.new("Some user agent")
  end

  def index_mobile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer bg-light text-dark fixed-bottom" style="margin-top: 5%; width:103%;">
<div class="container">
<div class="copyright text-center">
	<hr />
	<p style="font-size:1em;" class="small">&copy; 2016-2020, made with ❤</span> by Darukeru 
	|| Powered by:</strong>  <%= link_to 'Rails', 'https://rubyonrails.org/' %> 
	</p>
      <p> <a href="http://www.reddit.com/user/Darukeru" target="_blank"> <img src="https://www.redditstatic.com/spreddit1.gif" /> </a>
      <a href="http://www.twitter.com/Darukeru" target="_blank"> <img src="https://i.imgur.com/yoa240I.png" /> </a>
      </p>
</div>
</div>
</footer>
<script  type="text/javascript">



        
function calculate(){

	var a1= document.getElementById("a1");
	var a2= document.getElementById("a2");
	var a3= document.getElementById("a3");
	var a4= document.getElementById("a4");
	var a5= document.getElementById("a5");
	var a6= document.getElementById("a6");
	var a7= document.getElementById("a7");
	var a8= document.getElementById("a8");
	var a9= document.getElementById("a9");

	a2.value=(a1.value /8);
    a3.value=(a1.value /8192);
    a5.value=(a4.value /1024);
    a6.value=(a4.value *8);
    a8.value=(a7.value *1024);
    a9.value=(a7.value *8192);
};

	
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nintendo® Blocks to MegaBytes Converter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Fanwood+Text' rel='stylesheet' type='text/css'>

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
  
</head>
<body class="index">

<%= yield %>


</body>
<%= render :partial => 'layouts/footer' %>
</html>

app/views/welcome/index.html.erb
<% require "browser/aliases" %>
<% if !@browser.device.mobile? %>
	<% controller.redirect_to mobile_path %>
<% end 
%>


<div class="page-hero bg-primary text-white" id="banner">
	
	<center style="padding-bottom:3rem;">
<h1 class="title">Nintendo® Blocks to MegaBytes / GigaBytes Converter</h1>
</center>
	<div class="bubbles d-none d-md-block">
<!-- 				bubbles -->
      <div class="bubble bubble-1 rotate-bubble bg-warning"></div>
      <div class="bubble bubble-2 bubble-bottom-right bg-danger rotate-bubble"></div>
      <div class="bubble bubble-3 bubble-top-right bg-warning rotate-bubble"></div>
      <div class="bubble bubble-4 bubble-top-left bg-info rotate-bubble"></div>
      <div class="bubble bubble-5 bg-info rotate-bubble"></div>
      <div class="bubble bubble-6 bubble-bottom-right bg-danger rotate-bubble"></div>
      <div class="bubble bubble-7 bubble-top-right bg-success rotate-bubble"></div>
      <div class="bubble bubble-8 bubble-top-left bg-success rotate-bubble"></div>
      <div class="bubble bubble-9 bg-warning rotate-bubble"></div>
      <div class="bubble bubble-10 bg-danger rotate-bubble"></div>
      <div class="bubble bubble-11 bubble-bottom-right bg-info rotate-bubble"></div>
      <div class="bubble bubble-12 bubble-top-right bg-success rotate-bubble"></div>
      <div class="bubble bubble-13 bubble-top-left bg-success rotate-bubble"></div>
<!--         circles -->
      <div class="circle circle-1 bg-light rotate-circle"></div>
      <div class="circle circle-2 bg-success rotate-circle"></div>
      <div class="circle circle-3 bg-danger rotate-circle"></div>
      <div class="circle circle-4 bg-info rotate-circle"></div>
      <div class="circle circle-5 bg-success rotate-circle"></div>
      <div class="circle circle-6 bg-info rotate-circle"></div>
      <div class="circle circle-7 bg-warning rotate-circle"></div>
      <div class="circle circle-8 bg-white rotate-circle"></div>
      <div class="circle circle-9 bg-warning rotate-circle"></div>
      <div class="circle circle-10 bg-danger rotate-circle"></div>
	</div>

<div style="margin: 3%;">
	  
<div style="width:100%; margin:0 auto;">

<div class="row center-xs">
  <div class="col-xs-12	">
    <div id="parent" class="box" style="padding-bottom:5%;" >

    	<div class="div" style="padding-bottom:5%;">
			<form class="form" >
				<h3 style="padding-top:1%; padding-bottom:2%;">Blocks to MegaBytes/GigaBytes</h3>
				<div style="display: flex; flex-direction: row; padding-left:10%;">
				<input id="a1" type="text" value="" class="actions form-control2" placeholder="Blocks" onInput="calculate();" autofocus/>
				 <strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> Blocks  ➤ ➤ </strong> <input id="a2" type="text" value="Zero" class="color-box text-white actions form-control2" readonly/> 
				 <strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> MB </strong><input id="a3" type="text" value="Zero" class="color-box text-white actions form-control2" readonly/>
				  <strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> GB </strong>
				</div>

			</form>
		<form class="form" style="margin-top:2rem;">
			<h3 style="padding-top:1%; padding-bottom:2%;">MegaBytes to Blocks</h3>
			
			<div style="display: flex; flex-direction: row; padding-left:10%;">
			<input id="a4" type="text" value="" class="actions form-control2" placeholder="MegaBytes" onInput="calculate();" /> 
			<strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;">  MB  </strong> <input id="a5" type="text" value="Zero" class="color-box text-white actions form-control2" readonly/>
			 <strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> GB ➤ ➤</strong>  <input id="a6" type="text" value="Zero" class="color-box text-white actions form-control2" readonly/> 
			 <strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> Blocks</strong>
			</div>
		</form>

		<form class="form" style="margin-top:2rem;">
			<h3 style="padding-top:1%; padding-bottom:2%;">GigaBytes to Blocks</h3>
			
			<div style="display: flex; flex-direction: row; padding-left:10%;">
			<input id="a7" type="text" value="" class="actions form-control2" placeholder="GigaBytes" onInput="calculate();" />
			<strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> GB </strong> <input id="a8" type="text" value="Zero" class="color-box text-white actions form-control2" readonly/>
			<strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> MB </strong>  ➤ ➤ <input id="a9" type="text" value="Zero" class="color-box text-white actions form-control2" readonly/> 
			<strong class="myfont color-text-in" style="padding-top:1.5%; margin-left:1%; margin-right:1%;"> Blocks</strong>
			</div>
		</form>
		
		</div>
    </div>
  </div>
</div>
</div>
</div>

app/views/welcome/index2.html.erb
<div style="width:95%; margin:0 auto;">
<div class="row center-xs">
  <div class="col-xs-8 com-md-6">
		<h1 class="title">Nintendo® Blocks to MegaBytes/GigaBytes Converter</h1>
    <div id="parent" class="box" >

    	<div class="div">
			<form class="form">
				<h3 style="padding-top:1em;">Blocks to MegaBytes/GigaBytes</h3>
				<input id="a1" type="text" value="8" class="actions form-control" placeholder="Blocks"/> <strong>Blocks</strong> ➤ ➤ <input id="a2" type="text" value="1" class="actions form-control2" readonly/> <strong> MB </strong><input id="a3" type="text" value="0.0009765625" class="actions form-control2" readonly/> <strong> GB </strong>

			</form>
		<form class="form" style="margin-top:3em;">
			<h3>MegaBytes to Blocks</h3>
			<input id="a4" type="text" value="1" class="actions form-control" placeholder="MegaBytes" /> <strong> MB </strong> <input id="a5" type="text" value="0.0009765625" class="actions form-control2" readonly/> <strong> GB </strong> ➤ ➤ <input id="a6" type="text" value="8" class="actions form-control2" readonly/> <strong>Blocks</strong>
		</form>
		<form class="form" style="margin-top:3em;">
			<h3>GigaBytes to Blocks</h3>
			<input id="a7" type="text" value="1" class="actions form-control" placeholder="GigaBytes" /> <strong> GB </strong> <input id="a8" type="text" value="1024" class="actions form-control2" readonly/> <strong> MB </strong>  ➤ ➤ <input id="a9" type="text" value="8192" class="actions form-control2" readonly/> <strong>Blocks</strong>
		</form>
    	</div>
    </div>
  </div>
</div>
</div>

app/views/welcome/index_mobile.html.erb
	<div class="page-hero bg-primary text-white" id="banner">
	
	<center style="padding-bottom:1rem;">
<h2 class="title">Nintendo® Blocks to MegaBytes / GigaBytes Converter</h1>
</center>
		<div class="bubbles d-none d-md-block">
<!-- 				bubbles -->
      <div class="bubble bubble-1 rotate-bubble bg-warning"></div>
      <div class="bubble bubble-2 bubble-bottom-right bg-danger rotate-bubble"></div>
      <div class="bubble bubble-3 bubble-top-right bg-warning rotate-bubble"></div>
      <div class="bubble bubble-4 bubble-top-left bg-info rotate-bubble"></div>
      <div class="bubble bubble-5 bg-info rotate-bubble"></div>
      <div class="bubble bubble-6 bubble-bottom-right bg-danger rotate-bubble"></div>
      <div class="bubble bubble-7 bubble-top-right bg-success rotate-bubble"></div>
      <div class="bubble bubble-8 bubble-top-left bg-success rotate-bubble"></div>
      <div class="bubble bubble-9 bg-warning rotate-bubble"></div>
      <div class="bubble bubble-10 bg-danger rotate-bubble"></div>
      <div class="bubble bubble-11 bubble-bottom-right bg-info rotate-bubble"></div>
      <div class="bubble bubble-12 bubble-top-right bg-success rotate-bubble"></div>
      <div class="bubble bubble-13 bubble-top-left bg-success rotate-bubble"></div>
<!--         circles -->
      <div class="circle circle-1 bg-light rotate-circle"></div>
      <div class="circle circle-2 bg-success rotate-circle"></div>
      <div class="circle circle-3 bg-danger rotate-circle"></div>
      <div class="circle circle-4 bg-info rotate-circle"></div>
      <div class="circle circle-5 bg-success rotate-circle"></div>
      <div class="circle circle-6 bg-info rotate-circle"></div>
      <div class="circle circle-7 bg-warning rotate-circle"></div>
      <div class="circle circle-8 bg-white rotate-circle"></div>
      <div class="circle circle-9 bg-warning rotate-circle"></div>
      <div class="circle circle-10 bg-danger rotate-circle"></div>
		</div>
	  <div class="container">
	  
<div style="width:100%; margin:0 auto;">

<div class="row center-xs">
  <div class="col-xs-12">
    <div id="parent" class="box" style="padding-bottom:10%;" >

    	<div class="div" >
			<form class="form" >
				<h3 style="padding-top:1%; padding-bottom:2%;">Blocks to MegaBytes/GigaBytes</h3>
				<center>
				<div style="display: flex; flex-direction: column; padding:1%;">
				<input id="a1" type="text" value="" class="actions form-control-mobile" placeholder="Blocks" onInput="calculate();" autofocus/>
				 <strong class="myfont color-text-in" style="margin-bottom:5%;"> Blocks </strong> <input id="a2" type="text" value="Zero" class="color-box text-white actions form-control-mobile" readonly/> 
				 <strong class="myfont color-text-in" style="margin-bottom:5%;"> MB </strong><input id="a3" type="text" value="Zero" class="color-box text-white actions form-control-mobile" readonly/>
				  <strong class="myfont color-text-in" style="margin-bottom:5%;"> GB </strong>
				</div>
				</center>

			</form>
			
		<hr/>
		<form class="form" style="margin-top:3em;">
			<h3 style="padding-top:1%; padding-bottom:2%;">MegaBytes to Blocks</h3>
			
			<center>
			<div style="display: flex; flex-direction: column; padding:1%;">
			<input id="a4" type="text" value="" class="actions form-control-mobile" placeholder="MegaBytes" onInput="calculate();" /> 
			<strong class="myfont color-text-in" style="margin-bottom:5%;"> MB </strong> <input id="a5" type="text" value="Zero" class="color-box text-white actions form-control-mobile" readonly/>
			 <strong class="myfont color-text-in" style="margin-bottom:5%;"> GB </strong> ➤ ➤ <input id="a6" type="text" value="Zero" class="color-box text-white actions form-control-mobile" readonly/> 
			 <strong class="myfont color-text-in" style="margin-bottom:5%;"> Blocks</strong>
			</div>
			</center>
		</form>
		<hr/>
		<form class="form" style="margin-top:3em;">
			<h3 style="padding-top:1%; padding-bottom:2%;">GigaBytes to Blocks</h3>
			
			<center>
			<div style="display: flex; flex-direction: column; padding:1%;">
			<input id="a7" type="text" value="" class="actions form-control-mobile" placeholder="GigaBytes" onInput="calculate();" />
			 <strong class="myfont color-text-in" style="margin-bottom:5%;"> GB </strong> <input id="a8" type="text" value="Zero" class="color-box text-white actions form-control-mobile" readonly/>
			  <strong class="myfont color-text-in" style="margin-bottom:5%;"> MB </strong>  ➤ ➤ <input id="a9" type="text" value="Zero" class="color-box text-white actions form-control-mobile" readonly/> 
			  <strong class="myfont color-text-in" style="margin-bottom:5%;"> Blocks</strong>
			</div>
			</center>
		</form>
		
		</div>
    </div>
  </div>
</div>
</div>